-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- PROGRAM		"Quartus II 64-Bit"
-- VERSION		"Version 13.0.0 Build 156 04/24/2013 SJ Web Edition"
-- CREATED		"Tue Nov 24 18:13:27 2015"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY contr_MEF IS 
	PORT
	(
		Op :  IN  STD_LOGIC_VECTOR(5 DOWNTO 0);
		S :  IN  STD_LOGIC_VECTOR(3 DOWNTO 0);
		EscrevePC :  OUT  STD_LOGIC;
		EscrevePCCond :  OUT  STD_LOGIC;
		IouD :  OUT  STD_LOGIC;
		LeMem :  OUT  STD_LOGIC;
		EscreveMem :  OUT  STD_LOGIC;
		MemparaReg :  OUT  STD_LOGIC;
		EscreveIR :  OUT  STD_LOGIC;
		OrigAALU :  OUT  STD_LOGIC;
		EscreveReg :  OUT  STD_LOGIC;
		RegDst :  OUT  STD_LOGIC;
		BNE :  OUT  STD_LOGIC;
		LUI :  OUT  STD_LOGIC;
		NS :  OUT  STD_LOGIC_VECTOR(3 DOWNTO 0);
		OpALU :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0);
		OrigBALU :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0);
		OrigPc :  OUT  STD_LOGIC_VECTOR(1 DOWNTO 0)
	);
END contr_MEF;

ARCHITECTURE bdf_type OF contr_MEF IS 

SIGNAL	NS_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL	OpALU_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL	OrigBALU_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL	OrigPC_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_305 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_4 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_6 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_10 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_11 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_12 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_13 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_306 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_15 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_16 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_18 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_19 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_20 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_21 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_307 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_23 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_24 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_25 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_27 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_28 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_29 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_308 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_34 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_36 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_37 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_41 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_42 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_43 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_44 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_45 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_46 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_47 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_48 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_49 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_309 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_51 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_52 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_53 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_54 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_55 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_57 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_58 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_59 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_60 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_310 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_62 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_63 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_64 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_66 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_67 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_68 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_69 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_311 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_71 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_72 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_73 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_75 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_76 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_77 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_312 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_79 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_80 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_81 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_82 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_83 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_85 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_86 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_87 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_313 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_89 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_90 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_91 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_93 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_94 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_95 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_314 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_97 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_98 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_100 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_101 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_102 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_103 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_104 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_315 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_110 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_114 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_115 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_116 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_117 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_316 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_119 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_120 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_121 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_122 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_123 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_125 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_126 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_127 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_317 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_129 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_130 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_132 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_133 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_134 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_135 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_136 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_318 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_138 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_139 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_141 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_142 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_143 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_144 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_145 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_146 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_147 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_148 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_149 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_150 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_151 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_152 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_153 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_154 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_155 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_319 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_157 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_158 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_159 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_160 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_162 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_163 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_164 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_165 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_320 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_167 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_168 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_169 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_170 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_172 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_173 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_174 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_175 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_176 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_177 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_178 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_179 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_180 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_181 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_182 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_183 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_184 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_185 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_186 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_187 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_188 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_189 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_190 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_191 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_321 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_193 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_194 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_195 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_196 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_198 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_322 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_200 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_201 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_202 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_203 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_205 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_323 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_207 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_208 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_209 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_210 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_212 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_213 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_214 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_215 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_216 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_217 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_218 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_219 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_220 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_221 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_222 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_223 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_224 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_225 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_226 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_227 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_228 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_229 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_230 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_231 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_232 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_233 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_234 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_235 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_236 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_237 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_238 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_239 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_240 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_241 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_242 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_243 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_244 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_245 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_246 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_247 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_248 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_249 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_250 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_251 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_252 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_324 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_254 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_255 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_256 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_257 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_258 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_260 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_261 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_262 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_263 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_264 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_265 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_266 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_267 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_268 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_269 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_270 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_271 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_272 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_273 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_274 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_275 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_276 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_277 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_278 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_279 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_280 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_281 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_325 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_283 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_284 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_285 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_286 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_287 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_289 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_290 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_291 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_292 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_293 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_294 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_295 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_296 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_297 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_298 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_299 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_300 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_301 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_302 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_303 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_304 :  STD_LOGIC;


BEGIN 
SYNTHESIZED_WIRE_305 <= '1';
SYNTHESIZED_WIRE_306 <= '1';
SYNTHESIZED_WIRE_307 <= '1';
SYNTHESIZED_WIRE_308 <= '1';
SYNTHESIZED_WIRE_42 <= '0';
SYNTHESIZED_WIRE_309 <= '1';
SYNTHESIZED_WIRE_310 <= '1';
SYNTHESIZED_WIRE_311 <= '1';
SYNTHESIZED_WIRE_312 <= '1';
SYNTHESIZED_WIRE_313 <= '1';
SYNTHESIZED_WIRE_314 <= '1';
SYNTHESIZED_WIRE_315 <= '1';
SYNTHESIZED_WIRE_316 <= '1';
SYNTHESIZED_WIRE_317 <= '1';
SYNTHESIZED_WIRE_318 <= '1';
SYNTHESIZED_WIRE_319 <= '1';
SYNTHESIZED_WIRE_320 <= '1';
SYNTHESIZED_WIRE_321 <= '1';
SYNTHESIZED_WIRE_322 <= '1';
SYNTHESIZED_WIRE_323 <= '1';
SYNTHESIZED_WIRE_215 <= '0';
SYNTHESIZED_WIRE_224 <= '0';
SYNTHESIZED_WIRE_324 <= '1';
SYNTHESIZED_WIRE_325 <= '1';



SYNTHESIZED_WIRE_238 <= NOT(S(2) OR S(3) OR S(1) OR S(0));


SYNTHESIZED_WIRE_225 <= SYNTHESIZED_WIRE_305 AND SYNTHESIZED_WIRE_305 AND SYNTHESIZED_WIRE_305 AND SYNTHESIZED_WIRE_305 AND SYNTHESIZED_WIRE_4 AND SYNTHESIZED_WIRE_305 AND SYNTHESIZED_WIRE_6 AND S(1) AND SYNTHESIZED_WIRE_305 AND SYNTHESIZED_WIRE_305 AND SYNTHESIZED_WIRE_305 AND S(0);


SYNTHESIZED_WIRE_283 <= NOT(Op(5));



SYNTHESIZED_WIRE_290 <= NOT(Op(4));



SYNTHESIZED_WIRE_289 <= NOT(Op(3));



SYNTHESIZED_WIRE_285 <= NOT(Op(0));



SYNTHESIZED_WIRE_281 <= NOT(Op(1));



SYNTHESIZED_WIRE_83 <= NOT(S(1));



SYNTHESIZED_WIRE_4 <= NOT(S(2));



SYNTHESIZED_WIRE_6 <= NOT(S(3));



SYNTHESIZED_WIRE_80 <= NOT(S(2));



SYNTHESIZED_WIRE_82 <= NOT(S(3));



EscreveReg <= SYNTHESIZED_WIRE_10 OR SYNTHESIZED_WIRE_11 OR SYNTHESIZED_WIRE_12;


SYNTHESIZED_WIRE_79 <= NOT(Op(5));



SYNTHESIZED_WIRE_86 <= NOT(Op(4));



SYNTHESIZED_WIRE_85 <= NOT(Op(3));



SYNTHESIZED_WIRE_29 <= NOT(S(0));



SYNTHESIZED_WIRE_81 <= NOT(Op(0));



SYNTHESIZED_WIRE_25 <= NOT(S(3));




SYNTHESIZED_WIRE_76 <= NOT(Op(2));



SYNTHESIZED_WIRE_77 <= NOT(Op(1));



SYNTHESIZED_WIRE_229 <= SYNTHESIZED_WIRE_13 AND Op(1) AND SYNTHESIZED_WIRE_306 AND Op(5) AND SYNTHESIZED_WIRE_15 AND Op(0) AND SYNTHESIZED_WIRE_16 AND S(1) AND SYNTHESIZED_WIRE_306 AND Op(3) AND SYNTHESIZED_WIRE_18 AND SYNTHESIZED_WIRE_19;


SYNTHESIZED_WIRE_227 <= SYNTHESIZED_WIRE_20 AND SYNTHESIZED_WIRE_21 AND SYNTHESIZED_WIRE_307 AND SYNTHESIZED_WIRE_23 AND S(2) AND SYNTHESIZED_WIRE_24 AND SYNTHESIZED_WIRE_25 AND S(1) AND SYNTHESIZED_WIRE_307 AND SYNTHESIZED_WIRE_27 AND SYNTHESIZED_WIRE_28 AND SYNTHESIZED_WIRE_29;


SYNTHESIZED_WIRE_19 <= NOT(S(0));



SYNTHESIZED_WIRE_15 <= NOT(S(2));



SYNTHESIZED_WIRE_16 <= NOT(S(3));



SYNTHESIZED_WIRE_68 <= NOT(S(0));



SYNTHESIZED_WIRE_18 <= NOT(Op(4));



SYNTHESIZED_WIRE_300 <= NOT(S(1));



SYNTHESIZED_WIRE_64 <= NOT(S(3));




SYNTHESIZED_WIRE_13 <= NOT(Op(2));



SYNTHESIZED_WIRE_301 <= NOT(S(0));




SYNTHESIZED_WIRE_147 <= SYNTHESIZED_WIRE_308 AND SYNTHESIZED_WIRE_308 AND SYNTHESIZED_WIRE_308 AND SYNTHESIZED_WIRE_308 AND SYNTHESIZED_WIRE_34 AND SYNTHESIZED_WIRE_308 AND SYNTHESIZED_WIRE_36 AND SYNTHESIZED_WIRE_37 AND SYNTHESIZED_WIRE_308 AND SYNTHESIZED_WIRE_308 AND SYNTHESIZED_WIRE_308 AND SYNTHESIZED_WIRE_41;


SYNTHESIZED_WIRE_244 <= SYNTHESIZED_WIRE_42 OR SYNTHESIZED_WIRE_43 OR SYNTHESIZED_WIRE_44 OR SYNTHESIZED_WIRE_45 OR SYNTHESIZED_WIRE_46 OR SYNTHESIZED_WIRE_47;



SYNTHESIZED_WIRE_34 <= NOT(S(2));



SYNTHESIZED_WIRE_43 <= SYNTHESIZED_WIRE_48 AND SYNTHESIZED_WIRE_49 AND SYNTHESIZED_WIRE_309 AND SYNTHESIZED_WIRE_51 AND SYNTHESIZED_WIRE_52 AND SYNTHESIZED_WIRE_53 AND SYNTHESIZED_WIRE_54 AND SYNTHESIZED_WIRE_55 AND SYNTHESIZED_WIRE_309 AND SYNTHESIZED_WIRE_57 AND SYNTHESIZED_WIRE_58 AND S(0);


SYNTHESIZED_WIRE_55 <= NOT(S(1));



SYNTHESIZED_WIRE_52 <= NOT(S(2));



SYNTHESIZED_WIRE_54 <= NOT(S(3));



SYNTHESIZED_WIRE_51 <= NOT(Op(5));



SYNTHESIZED_WIRE_58 <= NOT(Op(4));



SYNTHESIZED_WIRE_44 <= SYNTHESIZED_WIRE_59 AND SYNTHESIZED_WIRE_60 AND SYNTHESIZED_WIRE_310 AND SYNTHESIZED_WIRE_62 AND S(2) AND SYNTHESIZED_WIRE_63 AND SYNTHESIZED_WIRE_64 AND S(1) AND SYNTHESIZED_WIRE_310 AND SYNTHESIZED_WIRE_66 AND SYNTHESIZED_WIRE_67 AND SYNTHESIZED_WIRE_68;


SYNTHESIZED_WIRE_57 <= NOT(Op(3));



SYNTHESIZED_WIRE_53 <= NOT(Op(0));




SYNTHESIZED_WIRE_48 <= NOT(Op(2));



SYNTHESIZED_WIRE_49 <= NOT(Op(1));



SYNTHESIZED_WIRE_46 <= SYNTHESIZED_WIRE_69 AND Op(1) AND SYNTHESIZED_WIRE_311 AND Op(5) AND SYNTHESIZED_WIRE_71 AND Op(0) AND SYNTHESIZED_WIRE_72 AND SYNTHESIZED_WIRE_73 AND SYNTHESIZED_WIRE_311 AND Op(3) AND SYNTHESIZED_WIRE_75 AND S(0);


SYNTHESIZED_WIRE_71 <= NOT(S(2));



SYNTHESIZED_WIRE_72 <= NOT(S(3));



SYNTHESIZED_WIRE_75 <= NOT(Op(4));




SYNTHESIZED_WIRE_228 <= SYNTHESIZED_WIRE_76 AND SYNTHESIZED_WIRE_77 AND SYNTHESIZED_WIRE_312 AND SYNTHESIZED_WIRE_79 AND SYNTHESIZED_WIRE_80 AND SYNTHESIZED_WIRE_81 AND SYNTHESIZED_WIRE_82 AND SYNTHESIZED_WIRE_83 AND SYNTHESIZED_WIRE_312 AND SYNTHESIZED_WIRE_85 AND SYNTHESIZED_WIRE_86 AND S(0);


SYNTHESIZED_WIRE_69 <= NOT(Op(2));



SYNTHESIZED_WIRE_73 <= NOT(S(1));



SYNTHESIZED_WIRE_36 <= NOT(S(3));



SYNTHESIZED_WIRE_45 <= SYNTHESIZED_WIRE_87 AND Op(1) AND SYNTHESIZED_WIRE_313 AND Op(5) AND SYNTHESIZED_WIRE_89 AND Op(0) AND SYNTHESIZED_WIRE_90 AND SYNTHESIZED_WIRE_91 AND SYNTHESIZED_WIRE_313 AND SYNTHESIZED_WIRE_93 AND SYNTHESIZED_WIRE_94 AND S(0);


SYNTHESIZED_WIRE_91 <= NOT(S(1));



SYNTHESIZED_WIRE_89 <= NOT(S(2));



SYNTHESIZED_WIRE_90 <= NOT(S(3));



SYNTHESIZED_WIRE_47 <= SYNTHESIZED_WIRE_95 AND Op(1) AND SYNTHESIZED_WIRE_314 AND Op(5) AND SYNTHESIZED_WIRE_97 AND Op(0) AND SYNTHESIZED_WIRE_98 AND S(1) AND SYNTHESIZED_WIRE_314 AND SYNTHESIZED_WIRE_100 AND SYNTHESIZED_WIRE_101 AND SYNTHESIZED_WIRE_102;


SYNTHESIZED_WIRE_94 <= NOT(Op(4));



SYNTHESIZED_WIRE_93 <= NOT(Op(3));



SYNTHESIZED_WIRE_134 <= S(3) AND SYNTHESIZED_WIRE_103 AND SYNTHESIZED_WIRE_104 AND S(0);


SYNTHESIZED_WIRE_102 <= NOT(S(0));




SYNTHESIZED_WIRE_87 <= NOT(Op(2));



SYNTHESIZED_WIRE_97 <= NOT(S(2));



SYNTHESIZED_WIRE_98 <= NOT(S(3));



SYNTHESIZED_WIRE_101 <= NOT(Op(4));



SYNTHESIZED_WIRE_100 <= NOT(Op(3));




SYNTHESIZED_WIRE_95 <= NOT(Op(2));



SYNTHESIZED_WIRE_264 <= NOT(S(0));



SYNTHESIZED_WIRE_103 <= NOT(S(2));



SYNTHESIZED_WIRE_37 <= NOT(S(1));



SYNTHESIZED_WIRE_41 <= NOT(S(0));



SYNTHESIZED_WIRE_149 <= SYNTHESIZED_WIRE_315 AND SYNTHESIZED_WIRE_315 AND SYNTHESIZED_WIRE_315 AND SYNTHESIZED_WIRE_315 AND S(2) AND SYNTHESIZED_WIRE_315 AND SYNTHESIZED_WIRE_110 AND S(1) AND SYNTHESIZED_WIRE_315 AND SYNTHESIZED_WIRE_315 AND SYNTHESIZED_WIRE_315 AND SYNTHESIZED_WIRE_114;


SYNTHESIZED_WIRE_114 <= NOT(S(0));



SYNTHESIZED_WIRE_110 <= NOT(S(3));



SYNTHESIZED_WIRE_303 <= S(3) AND SYNTHESIZED_WIRE_115 AND S(1) AND SYNTHESIZED_WIRE_116;


SYNTHESIZED_WIRE_148 <= SYNTHESIZED_WIRE_117 AND Op(1) AND SYNTHESIZED_WIRE_316 AND SYNTHESIZED_WIRE_119 AND SYNTHESIZED_WIRE_120 AND SYNTHESIZED_WIRE_121 AND SYNTHESIZED_WIRE_122 AND SYNTHESIZED_WIRE_123 AND SYNTHESIZED_WIRE_316 AND SYNTHESIZED_WIRE_125 AND SYNTHESIZED_WIRE_126 AND S(0);


SYNTHESIZED_WIRE_123 <= NOT(S(1));



SYNTHESIZED_WIRE_120 <= NOT(S(2));



SYNTHESIZED_WIRE_122 <= NOT(S(3));



SYNTHESIZED_WIRE_104 <= NOT(S(1));



SYNTHESIZED_WIRE_119 <= NOT(Op(5));



SYNTHESIZED_WIRE_126 <= NOT(Op(4));



SYNTHESIZED_WIRE_125 <= NOT(Op(3));



SYNTHESIZED_WIRE_121 <= NOT(Op(0));




SYNTHESIZED_WIRE_117 <= NOT(Op(2));



SYNTHESIZED_WIRE_150 <= SYNTHESIZED_WIRE_127 AND Op(1) AND SYNTHESIZED_WIRE_317 AND Op(5) AND SYNTHESIZED_WIRE_129 AND Op(0) AND SYNTHESIZED_WIRE_130 AND S(1) AND SYNTHESIZED_WIRE_317 AND Op(3) AND SYNTHESIZED_WIRE_132 AND SYNTHESIZED_WIRE_133;


SYNTHESIZED_WIRE_129 <= NOT(S(2));



SYNTHESIZED_WIRE_130 <= NOT(S(3));



SYNTHESIZED_WIRE_132 <= NOT(Op(4));



EscrevePC <= SYNTHESIZED_WIRE_134 OR SYNTHESIZED_WIRE_135;



SYNTHESIZED_WIRE_127 <= NOT(Op(2));



SYNTHESIZED_WIRE_133 <= NOT(S(0));



SYNTHESIZED_WIRE_151 <= SYNTHESIZED_WIRE_136 AND Op(1) AND SYNTHESIZED_WIRE_318 AND Op(5) AND SYNTHESIZED_WIRE_138 AND Op(0) AND SYNTHESIZED_WIRE_139 AND S(1) AND SYNTHESIZED_WIRE_318 AND SYNTHESIZED_WIRE_141 AND SYNTHESIZED_WIRE_142 AND SYNTHESIZED_WIRE_143;


SYNTHESIZED_WIRE_138 <= NOT(S(2));



SYNTHESIZED_WIRE_139 <= NOT(S(3));



SYNTHESIZED_WIRE_142 <= NOT(Op(4));



SYNTHESIZED_WIRE_141 <= NOT(Op(3));




SYNTHESIZED_WIRE_136 <= NOT(Op(2));



EscreveIR <= NOT(S(2) OR S(3) OR S(1) OR S(0));


SYNTHESIZED_WIRE_191 <= S(3) AND SYNTHESIZED_WIRE_144 AND SYNTHESIZED_WIRE_145 AND SYNTHESIZED_WIRE_146;


SYNTHESIZED_WIRE_143 <= NOT(S(0));



NS_ALTERA_SYNTHESIZED(0) <= SYNTHESIZED_WIRE_147 OR SYNTHESIZED_WIRE_148 OR SYNTHESIZED_WIRE_149 OR SYNTHESIZED_WIRE_150 OR SYNTHESIZED_WIRE_151 OR SYNTHESIZED_WIRE_152;


BNE <= S(3) AND SYNTHESIZED_WIRE_153 AND S(1) AND SYNTHESIZED_WIRE_154;


SYNTHESIZED_WIRE_219 <= Op(2) AND SYNTHESIZED_WIRE_155 AND SYNTHESIZED_WIRE_319 AND SYNTHESIZED_WIRE_157 AND SYNTHESIZED_WIRE_158 AND Op(0) AND SYNTHESIZED_WIRE_159 AND SYNTHESIZED_WIRE_160 AND SYNTHESIZED_WIRE_319 AND SYNTHESIZED_WIRE_162 AND SYNTHESIZED_WIRE_163 AND S(0);


SYNTHESIZED_WIRE_160 <= NOT(S(1));



SYNTHESIZED_WIRE_158 <= NOT(S(2));



SYNTHESIZED_WIRE_159 <= NOT(S(3));



SYNTHESIZED_WIRE_157 <= NOT(Op(5));



SYNTHESIZED_WIRE_163 <= NOT(Op(4));



SYNTHESIZED_WIRE_162 <= NOT(Op(3));



SYNTHESIZED_WIRE_144 <= NOT(S(2));



SYNTHESIZED_WIRE_217 <= S(3) AND SYNTHESIZED_WIRE_164 AND S(1) AND S(0);



SYNTHESIZED_WIRE_155 <= NOT(Op(1));



SYNTHESIZED_WIRE_242 <= Op(2) AND SYNTHESIZED_WIRE_165 AND SYNTHESIZED_WIRE_320 AND SYNTHESIZED_WIRE_167 AND SYNTHESIZED_WIRE_168 AND Op(0) AND SYNTHESIZED_WIRE_169 AND SYNTHESIZED_WIRE_170 AND SYNTHESIZED_WIRE_320 AND SYNTHESIZED_WIRE_172 AND SYNTHESIZED_WIRE_173 AND S(0);


SYNTHESIZED_WIRE_170 <= NOT(S(1));



SYNTHESIZED_WIRE_168 <= NOT(S(2));



SYNTHESIZED_WIRE_169 <= NOT(S(3));



SYNTHESIZED_WIRE_167 <= NOT(Op(5));



SYNTHESIZED_WIRE_173 <= NOT(Op(4));



SYNTHESIZED_WIRE_172 <= NOT(Op(3));



SYNTHESIZED_WIRE_145 <= NOT(S(1));




SYNTHESIZED_WIRE_165 <= NOT(Op(1));



SYNTHESIZED_WIRE_153 <= NOT(S(2));



SYNTHESIZED_WIRE_154 <= NOT(S(0));



SYNTHESIZED_WIRE_23 <= NOT(Op(5));



SYNTHESIZED_WIRE_28 <= NOT(Op(4));



SYNTHESIZED_WIRE_27 <= NOT(Op(3));



SYNTHESIZED_WIRE_20 <= NOT(Op(2));



SYNTHESIZED_WIRE_21 <= NOT(Op(1));



SYNTHESIZED_WIRE_24 <= NOT(Op(0));



SYNTHESIZED_WIRE_146 <= NOT(S(0));




SYNTHESIZED_WIRE_176 <= S(3) AND SYNTHESIZED_WIRE_174 AND S(1) AND SYNTHESIZED_WIRE_175;


SYNTHESIZED_WIRE_115 <= NOT(S(2));



SYNTHESIZED_WIRE_116 <= NOT(S(0));



SYNTHESIZED_WIRE_174 <= NOT(S(2));



SYNTHESIZED_WIRE_175 <= NOT(S(0));



OpALU_ALTERA_SYNTHESIZED(0) <= SYNTHESIZED_WIRE_176 OR SYNTHESIZED_WIRE_177;



SYNTHESIZED_WIRE_62 <= NOT(Op(5));



SYNTHESIZED_WIRE_67 <= NOT(Op(4));



SYNTHESIZED_WIRE_213 <= SYNTHESIZED_WIRE_178 AND S(2) AND SYNTHESIZED_WIRE_179 AND S(0);


SYNTHESIZED_WIRE_66 <= NOT(Op(3));



SYNTHESIZED_WIRE_59 <= NOT(Op(2));



SYNTHESIZED_WIRE_60 <= NOT(Op(1));



SYNTHESIZED_WIRE_63 <= NOT(Op(0));



SYNTHESIZED_WIRE_184 <= S(3) AND SYNTHESIZED_WIRE_180 AND S(1) AND SYNTHESIZED_WIRE_181;


SYNTHESIZED_WIRE_180 <= NOT(S(2));



SYNTHESIZED_WIRE_181 <= NOT(S(0));




OrigAALU <= SYNTHESIZED_WIRE_182 OR SYNTHESIZED_WIRE_183 OR SYNTHESIZED_WIRE_184 OR SYNTHESIZED_WIRE_185;


SYNTHESIZED_WIRE_190 <= S(3) AND SYNTHESIZED_WIRE_186 AND S(1) AND SYNTHESIZED_WIRE_187;


EscreveMem <= SYNTHESIZED_WIRE_188 AND S(2) AND SYNTHESIZED_WIRE_189 AND S(0);


SYNTHESIZED_WIRE_186 <= NOT(S(2));



SYNTHESIZED_WIRE_187 <= NOT(S(0));



EscrevePCCond <= SYNTHESIZED_WIRE_190 OR SYNTHESIZED_WIRE_191;



SYNTHESIZED_WIRE_152 <= Op(2) AND Op(1) AND SYNTHESIZED_WIRE_321 AND SYNTHESIZED_WIRE_193 AND SYNTHESIZED_WIRE_194 AND Op(0) AND SYNTHESIZED_WIRE_195 AND SYNTHESIZED_WIRE_196 AND SYNTHESIZED_WIRE_321 AND Op(3) AND SYNTHESIZED_WIRE_198 AND S(0);


SYNTHESIZED_WIRE_196 <= NOT(S(1));



SYNTHESIZED_WIRE_194 <= NOT(S(2));



SYNTHESIZED_WIRE_195 <= NOT(S(3));



SYNTHESIZED_WIRE_193 <= NOT(Op(5));



SYNTHESIZED_WIRE_198 <= NOT(Op(4));



SYNTHESIZED_WIRE_178 <= NOT(S(3));



SYNTHESIZED_WIRE_243 <= Op(2) AND Op(1) AND SYNTHESIZED_WIRE_322 AND SYNTHESIZED_WIRE_200 AND SYNTHESIZED_WIRE_201 AND Op(0) AND SYNTHESIZED_WIRE_202 AND SYNTHESIZED_WIRE_203 AND SYNTHESIZED_WIRE_322 AND Op(3) AND SYNTHESIZED_WIRE_205 AND S(0);


SYNTHESIZED_WIRE_203 <= NOT(S(1));




SYNTHESIZED_WIRE_201 <= NOT(S(2));



SYNTHESIZED_WIRE_202 <= NOT(S(3));



SYNTHESIZED_WIRE_200 <= NOT(Op(5));



SYNTHESIZED_WIRE_205 <= NOT(Op(4));




SYNTHESIZED_WIRE_220 <= Op(2) AND Op(1) AND SYNTHESIZED_WIRE_323 AND SYNTHESIZED_WIRE_207 AND SYNTHESIZED_WIRE_208 AND Op(0) AND SYNTHESIZED_WIRE_209 AND SYNTHESIZED_WIRE_210 AND SYNTHESIZED_WIRE_323 AND Op(3) AND SYNTHESIZED_WIRE_212 AND S(0);


SYNTHESIZED_WIRE_210 <= NOT(S(1));



IouD <= SYNTHESIZED_WIRE_213 OR SYNTHESIZED_WIRE_214;


SYNTHESIZED_WIRE_208 <= NOT(S(2));



SYNTHESIZED_WIRE_209 <= NOT(S(3));



SYNTHESIZED_WIRE_207 <= NOT(Op(5));



SYNTHESIZED_WIRE_212 <= NOT(Op(4));




SYNTHESIZED_WIRE_164 <= NOT(S(2));



NS_ALTERA_SYNTHESIZED(3) <= SYNTHESIZED_WIRE_215 OR SYNTHESIZED_WIRE_216 OR SYNTHESIZED_WIRE_217 OR SYNTHESIZED_WIRE_218 OR SYNTHESIZED_WIRE_219 OR SYNTHESIZED_WIRE_220;



SYNTHESIZED_WIRE_226 <= S(3) AND SYNTHESIZED_WIRE_221 AND S(1) AND S(0);


SYNTHESIZED_WIRE_221 <= NOT(S(2));



SYNTHESIZED_WIRE_214 <= SYNTHESIZED_WIRE_222 AND SYNTHESIZED_WIRE_223 AND S(1) AND S(0);



NS_ALTERA_SYNTHESIZED(2) <= SYNTHESIZED_WIRE_224 OR SYNTHESIZED_WIRE_225 OR SYNTHESIZED_WIRE_226 OR SYNTHESIZED_WIRE_227 OR SYNTHESIZED_WIRE_228 OR SYNTHESIZED_WIRE_229;


LUI <= S(3) AND SYNTHESIZED_WIRE_230 AND S(1) AND S(0);


SYNTHESIZED_WIRE_230 <= NOT(S(2));



SYNTHESIZED_WIRE_135 <= SYNTHESIZED_WIRE_231 AND SYNTHESIZED_WIRE_232 AND SYNTHESIZED_WIRE_233 AND SYNTHESIZED_WIRE_234;


SYNTHESIZED_WIRE_232 <= NOT(S(2));



SYNTHESIZED_WIRE_233 <= NOT(S(1));



SYNTHESIZED_WIRE_234 <= NOT(S(0));



SYNTHESIZED_WIRE_231 <= NOT(S(3));



SYNTHESIZED_WIRE_223 <= NOT(S(2));



SYNTHESIZED_WIRE_277 <= NOT(S(2) OR S(3) OR S(1) OR S(0));


SYNTHESIZED_WIRE_222 <= NOT(S(3));



SYNTHESIZED_WIRE_179 <= NOT(S(1));



SYNTHESIZED_WIRE_237 <= SYNTHESIZED_WIRE_235 AND SYNTHESIZED_WIRE_236 AND S(1) AND S(0);


SYNTHESIZED_WIRE_236 <= NOT(S(2));



SYNTHESIZED_WIRE_235 <= NOT(S(3));



LeMem <= SYNTHESIZED_WIRE_237 OR SYNTHESIZED_WIRE_238;


SYNTHESIZED_WIRE_188 <= NOT(S(3));



SYNTHESIZED_WIRE_189 <= NOT(S(1));



MemparaReg <= SYNTHESIZED_WIRE_239 AND S(2) AND SYNTHESIZED_WIRE_240 AND SYNTHESIZED_WIRE_241;


SYNTHESIZED_WIRE_239 <= NOT(S(3));



NS_ALTERA_SYNTHESIZED(1) <= SYNTHESIZED_WIRE_242 OR SYNTHESIZED_WIRE_243 OR SYNTHESIZED_WIRE_244;


SYNTHESIZED_WIRE_240 <= NOT(S(1));



SYNTHESIZED_WIRE_241 <= NOT(S(0));



OrigPC_ALTERA_SYNTHESIZED(1) <= S(3) AND SYNTHESIZED_WIRE_245 AND SYNTHESIZED_WIRE_246 AND S(0);


SYNTHESIZED_WIRE_304 <= S(3) AND SYNTHESIZED_WIRE_247 AND SYNTHESIZED_WIRE_248 AND SYNTHESIZED_WIRE_249;


SYNTHESIZED_WIRE_246 <= NOT(S(1));



SYNTHESIZED_WIRE_245 <= NOT(S(2));



SYNTHESIZED_WIRE_248 <= NOT(S(1));



SYNTHESIZED_WIRE_247 <= NOT(S(2));



SYNTHESIZED_WIRE_249 <= NOT(S(0));



OpALU_ALTERA_SYNTHESIZED(1) <= SYNTHESIZED_WIRE_250 AND S(2) AND S(1) AND SYNTHESIZED_WIRE_251;


SYNTHESIZED_WIRE_216 <= SYNTHESIZED_WIRE_252 AND Op(1) AND SYNTHESIZED_WIRE_324 AND SYNTHESIZED_WIRE_254 AND SYNTHESIZED_WIRE_255 AND SYNTHESIZED_WIRE_256 AND SYNTHESIZED_WIRE_257 AND SYNTHESIZED_WIRE_258 AND SYNTHESIZED_WIRE_324 AND SYNTHESIZED_WIRE_260 AND SYNTHESIZED_WIRE_261 AND S(0);


SYNTHESIZED_WIRE_250 <= NOT(S(3));



SYNTHESIZED_WIRE_177 <= S(3) AND SYNTHESIZED_WIRE_262 AND SYNTHESIZED_WIRE_263 AND SYNTHESIZED_WIRE_264;


SYNTHESIZED_WIRE_251 <= NOT(S(0));



SYNTHESIZED_WIRE_272 <= SYNTHESIZED_WIRE_265 AND SYNTHESIZED_WIRE_266 AND SYNTHESIZED_WIRE_267 AND S(0);


SYNTHESIZED_WIRE_263 <= NOT(S(1));



SYNTHESIZED_WIRE_262 <= NOT(S(2));



SYNTHESIZED_WIRE_267 <= NOT(S(1));



SYNTHESIZED_WIRE_266 <= NOT(S(2));



SYNTHESIZED_WIRE_265 <= NOT(S(3));



SYNTHESIZED_WIRE_271 <= SYNTHESIZED_WIRE_268 AND SYNTHESIZED_WIRE_269 AND S(1) AND SYNTHESIZED_WIRE_270;



SYNTHESIZED_WIRE_270 <= NOT(S(0));



SYNTHESIZED_WIRE_269 <= NOT(S(2));



SYNTHESIZED_WIRE_268 <= NOT(S(3));



OrigBALU_ALTERA_SYNTHESIZED(1) <= SYNTHESIZED_WIRE_271 OR SYNTHESIZED_WIRE_272;


SYNTHESIZED_WIRE_276 <= SYNTHESIZED_WIRE_273 AND SYNTHESIZED_WIRE_274 AND SYNTHESIZED_WIRE_275 AND S(0);


SYNTHESIZED_WIRE_275 <= NOT(S(1));



SYNTHESIZED_WIRE_274 <= NOT(S(2));



SYNTHESIZED_WIRE_273 <= NOT(S(3));



OrigBALU_ALTERA_SYNTHESIZED(0) <= SYNTHESIZED_WIRE_276 OR SYNTHESIZED_WIRE_277;


SYNTHESIZED_WIRE_182 <= SYNTHESIZED_WIRE_278 AND SYNTHESIZED_WIRE_279 AND S(1) AND SYNTHESIZED_WIRE_280;


SYNTHESIZED_WIRE_218 <= Op(2) AND SYNTHESIZED_WIRE_281 AND SYNTHESIZED_WIRE_325 AND SYNTHESIZED_WIRE_283 AND SYNTHESIZED_WIRE_284 AND SYNTHESIZED_WIRE_285 AND SYNTHESIZED_WIRE_286 AND SYNTHESIZED_WIRE_287 AND SYNTHESIZED_WIRE_325 AND SYNTHESIZED_WIRE_289 AND SYNTHESIZED_WIRE_290 AND S(0);


SYNTHESIZED_WIRE_279 <= NOT(S(2));



SYNTHESIZED_WIRE_278 <= NOT(S(3));



SYNTHESIZED_WIRE_280 <= NOT(S(0));



SYNTHESIZED_WIRE_185 <= SYNTHESIZED_WIRE_291 AND S(2) AND S(1) AND SYNTHESIZED_WIRE_292;


SYNTHESIZED_WIRE_291 <= NOT(S(3));



SYNTHESIZED_WIRE_292 <= NOT(S(0));



SYNTHESIZED_WIRE_183 <= S(3) AND SYNTHESIZED_WIRE_293 AND SYNTHESIZED_WIRE_294 AND SYNTHESIZED_WIRE_295;


SYNTHESIZED_WIRE_294 <= NOT(S(1));



SYNTHESIZED_WIRE_293 <= NOT(S(2));



SYNTHESIZED_WIRE_295 <= NOT(S(0));




SYNTHESIZED_WIRE_10 <= SYNTHESIZED_WIRE_296 AND S(2) AND SYNTHESIZED_WIRE_297 AND SYNTHESIZED_WIRE_298;


SYNTHESIZED_WIRE_297 <= NOT(S(1));



SYNTHESIZED_WIRE_296 <= NOT(S(3));



SYNTHESIZED_WIRE_298 <= NOT(S(0));



SYNTHESIZED_WIRE_11 <= SYNTHESIZED_WIRE_299 AND S(2) AND S(1) AND S(0);


SYNTHESIZED_WIRE_12 <= S(3) AND S(2) AND SYNTHESIZED_WIRE_300 AND SYNTHESIZED_WIRE_301;


RegDst <= SYNTHESIZED_WIRE_302 AND S(2) AND S(1) AND S(0);


SYNTHESIZED_WIRE_299 <= NOT(S(3));



SYNTHESIZED_WIRE_302 <= NOT(S(3));



SYNTHESIZED_WIRE_258 <= NOT(S(1));



OrigPC_ALTERA_SYNTHESIZED(0) <= SYNTHESIZED_WIRE_303 OR SYNTHESIZED_WIRE_304;


SYNTHESIZED_WIRE_255 <= NOT(S(2));



SYNTHESIZED_WIRE_257 <= NOT(S(3));



SYNTHESIZED_WIRE_254 <= NOT(Op(5));



SYNTHESIZED_WIRE_261 <= NOT(Op(4));



SYNTHESIZED_WIRE_260 <= NOT(Op(3));



SYNTHESIZED_WIRE_256 <= NOT(Op(0));



SYNTHESIZED_WIRE_252 <= NOT(Op(2));



SYNTHESIZED_WIRE_287 <= NOT(S(1));



SYNTHESIZED_WIRE_284 <= NOT(S(2));



SYNTHESIZED_WIRE_286 <= NOT(S(3));


NS <= NS_ALTERA_SYNTHESIZED;
OpALU <= OpALU_ALTERA_SYNTHESIZED;
OrigBALU <= OrigBALU_ALTERA_SYNTHESIZED;
OrigPc <= OrigPC_ALTERA_SYNTHESIZED;

END bdf_type;